require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ResellersController do

  def mock_reseller(stubs={})
    @mock_reseller ||= mock_model(Reseller, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all resellers as @resellers" do
      Reseller.stub(:all) { [mock_reseller] }
      get :index
      assigns(:resellers).should eq([mock_reseller])
    end
  end

  describe "GET show" do
    it "assigns the requested reseller as @reseller" do
      Reseller.stub(:find).with("37") { mock_reseller }
      get :show, :id => "37"
      assigns(:reseller).should be(mock_reseller)
    end
  end

  describe "GET new" do
    it "assigns a new reseller as @reseller" do
      Reseller.stub(:new) { mock_reseller }
      get :new
      assigns(:reseller).should be(mock_reseller)
    end
  end

  describe "GET edit" do
    it "assigns the requested reseller as @reseller" do
      Reseller.stub(:find).with("37") { mock_reseller }
      get :edit, :id => "37"
      assigns(:reseller).should be(mock_reseller)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created reseller as @reseller" do
        Reseller.stub(:new).with({'these' => 'params'}) { mock_reseller(:save => true) }
        post :create, :reseller => {'these' => 'params'}
        assigns(:reseller).should be(mock_reseller)
      end

      it "redirects to the created reseller" do
        Reseller.stub(:new) { mock_reseller(:save => true) }
        post :create, :reseller => {}
        response.should redirect_to(reseller_url(mock_reseller))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reseller as @reseller" do
        Reseller.stub(:new).with({'these' => 'params'}) { mock_reseller(:save => false) }
        post :create, :reseller => {'these' => 'params'}
        assigns(:reseller).should be(mock_reseller)
      end

      it "re-renders the 'new' template" do
        Reseller.stub(:new) { mock_reseller(:save => false) }
        post :create, :reseller => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reseller" do
        Reseller.stub(:find).with("37") { mock_reseller }
        mock_reseller.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :reseller => {'these' => 'params'}
      end

      it "assigns the requested reseller as @reseller" do
        Reseller.stub(:find) { mock_reseller(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:reseller).should be(mock_reseller)
      end

      it "redirects to the reseller" do
        Reseller.stub(:find) { mock_reseller(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(reseller_url(mock_reseller))
      end
    end

    describe "with invalid params" do
      it "assigns the reseller as @reseller" do
        Reseller.stub(:find) { mock_reseller(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:reseller).should be(mock_reseller)
      end

      it "re-renders the 'edit' template" do
        Reseller.stub(:find) { mock_reseller(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reseller" do
      Reseller.stub(:find).with("37") { mock_reseller }
      mock_reseller.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the resellers list" do
      Reseller.stub(:find) { mock_reseller }
      delete :destroy, :id => "1"
      response.should redirect_to(resellers_url)
    end
  end

end
