require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RewardsController do

  def mock_reward(stubs={})
    @mock_reward ||= mock_model(Reward, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all rewards as @rewards" do
      Reward.stub(:all) { [mock_reward] }
      get :index
      assigns(:rewards).should eq([mock_reward])
    end
  end

  describe "GET show" do
    it "assigns the requested reward as @reward" do
      Reward.stub(:find).with("37") { mock_reward }
      get :show, :id => "37"
      assigns(:reward).should be(mock_reward)
    end
  end

  describe "GET new" do
    it "assigns a new reward as @reward" do
      Reward.stub(:new) { mock_reward }
      get :new
      assigns(:reward).should be(mock_reward)
    end
  end

  describe "GET edit" do
    it "assigns the requested reward as @reward" do
      Reward.stub(:find).with("37") { mock_reward }
      get :edit, :id => "37"
      assigns(:reward).should be(mock_reward)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created reward as @reward" do
        Reward.stub(:new).with({'these' => 'params'}) { mock_reward(:save => true) }
        post :create, :reward => {'these' => 'params'}
        assigns(:reward).should be(mock_reward)
      end

      it "redirects to the created reward" do
        Reward.stub(:new) { mock_reward(:save => true) }
        post :create, :reward => {}
        response.should redirect_to(reward_url(mock_reward))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reward as @reward" do
        Reward.stub(:new).with({'these' => 'params'}) { mock_reward(:save => false) }
        post :create, :reward => {'these' => 'params'}
        assigns(:reward).should be(mock_reward)
      end

      it "re-renders the 'new' template" do
        Reward.stub(:new) { mock_reward(:save => false) }
        post :create, :reward => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reward" do
        Reward.stub(:find).with("37") { mock_reward }
        mock_reward.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :reward => {'these' => 'params'}
      end

      it "assigns the requested reward as @reward" do
        Reward.stub(:find) { mock_reward(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:reward).should be(mock_reward)
      end

      it "redirects to the reward" do
        Reward.stub(:find) { mock_reward(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(reward_url(mock_reward))
      end
    end

    describe "with invalid params" do
      it "assigns the reward as @reward" do
        Reward.stub(:find) { mock_reward(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:reward).should be(mock_reward)
      end

      it "re-renders the 'edit' template" do
        Reward.stub(:find) { mock_reward(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reward" do
      Reward.stub(:find).with("37") { mock_reward }
      mock_reward.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the rewards list" do
      Reward.stub(:find) { mock_reward }
      delete :destroy, :id => "1"
      response.should redirect_to(rewards_url)
    end
  end

end
